name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ secrets.REGISTRY_URL }}/formula4-frontend:latest
          ${{ secrets.REGISTRY_URL }}/formula4-frontend:${{ github.sha }}
    
    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: ./api
        push: true
        tags: |
          ${{ secrets.REGISTRY_URL }}/formula4-api:latest
          ${{ secrets.REGISTRY_URL }}/formula4-api:${{ github.sha }}
    
    - name: Build and push data-processing image
      uses: docker/build-push-action@v5
      with:
        context: ./data-processing
        push: true
        tags: |
          ${{ secrets.REGISTRY_URL }}/formula4-data:latest
          ${{ secrets.REGISTRY_URL }}/formula4-data:${{ github.sha }}
    
    - name: Deploy to production
      run: |
        echo "Deployment configuration would go here"
        echo "This could include:"
        echo "- SSH to production server"
        echo "- Pull latest images"
        echo "- Run docker-compose up -d"
        echo "- Health checks"
        echo "- Rollback on failure" 